version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    container_name: pg_graphile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
